Developing
Bronzza/BasicShop pull request #1
Opened 2019-06-10 16:50 UTC by Bronzza

2019-06-11 08:09 UTC, Taniann requested changes
please resolve comments

2019-06-11 08:09 UTC, Taniann commented on src/main/java/MateAcad/BasicShop/Entities/Producer.java
> +
remove redundant blank line

2019-06-11 08:09 UTC, Taniann commented on src/main/java/MateAcad/BasicShop/Entities/Producer.java
> +    private Set<Product> products;
do you have overridden methods equals and hashcode in Product class?

2019-06-12 08:26 UTC, Bronzza commented on src/main/java/MateAcad/BasicShop/Entities/Producer.java
> +    private Set<Product> products;
after corrections added by lombok annotation

2019-06-12 12:40 UTC, Taniann approved these changes
good

2019-06-26 08:33 UTC, merged